### ISSUE TITLE
sinatra 2.8.0.1 fails with "cannot load such file -- bigdecimal"

### ISSUE THREAD

**Issue by drnic** [colstrom/concourse-resource-rubygems#3]
With the following pipeline:

```yaml
jobs:
  - name: rubygem-sinatra
    plan:
      - {get: rubygem-sinatra, trigger: true}

resources:
  - name: rubygem-sinatra
    type: rubygems
    check_every: 60m
    source:
      gem: sinatra
      api_key: ((rubygems-api-key))

resource_types:
  - name: rubygems
    type: docker-image
    source:
      repository: resource/rubygems
```

The `rubygem-sinatra` job fails to get the resource with the following error:

```
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bigdecimal (LoadError)
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/gems/2.5.0/gems/multi_xml-0.6.0/lib/multi_xml.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/gems/2.5.0/gems/httparty-0.18.0/lib/httparty.rb:6:in `<top (required)>'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/gems/2.5.0/gems/concourse-resource-rubygems-0.4.6/lib/concourse-resource/rubygems/in.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /opt/resource/in:3:in `<main>'
```

I tried rebuilding the docker image with newer gems, and the result is the one above. It's the same, but slightly newer httparty gem.
